### PR TITLE
Delete julia-tan.png

### PR DESCRIPTION
**Pull request by MasonProtter**
I think this image should not be in an official JuliaLang repository. In addition to being a rather controversial art style, it seems to violate the community code of conduct:

> In particular, do not sexualize the term "Julia" or any other aspects of the project. While "Julia" is a female name in many parts of the world, the programming language is not a person and does not have a gender.

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
+goodwill

**Comment by oxinabox** [comment]
It may or may not be against the code of conduct, but removing it makes it obvious that it is not. And will not be used to.

If you avoid personification, then you can trivially avoid sexualization. We don’t need to get anywhere near that. It isn’t useful.

**Comment by JeffBezanson** [comment]
Agree it should be removed. Unlike every other image in this repo, this one is not the julia logo and is not official in any way. It also has a different creator and copyright, which is mentioned in the readme but not in the license file, which is confusing.

In Japan it is common to have character (キャラ) mascots for almost everything, so this should be understood in context, and is acceptable IMO. It's just not a julia "logo" and is not endorsed by the project or community as a whole, which would separate it from that context.

**Comment by StefanKarpinski** [comment]
This repo was originally @cormullion's personal repo, at which point it made perfect sense to have Julia-tan in here, but now that it's been moved to @JuliaLang, giving it an official status, it should be removed (as it now has been). It is fine for people to use Julia-tan in a non-official capacity.

**Pull request merged**
